### ISSUE TITLE
El select no funciona

### ISSUE THREAD

**Issue by lmagarin** [Javierfs94/Reentrega-Formulario-Completito#1]

**Comment by Javierfs94** [comment]
No comprendo que no funciona.

 Lo estoy revisando y cuando eliges una de las opciones de idiomas (español, inglés o francés) si funciona. La otra opción es la que tengo por defecto con la que me aseguro de que se haya elegido al menos una.

Explíqueme cuando pueda para solucionarlo :)

**Comment by Javierfs94** [comment]
Cerrado en el issue #2
