### ISSUE TITLE
No entiendo 

### ISSUE THREAD

**Issue by lmagarin** [Javierfs94/Reentrega-Formulario-Completito#12]
/^([A-Z][a-z]{2,}\s[a-zA-z]{1,}**'?-?**[a-zA-Z]{2,}\s?([a-zA-Z]{1,})?)$/,

No entiendo tu expresión regular. ¿Cuántos nombres puede tener? Y guiones???
Mira lo que está en negrita

**Comment by Javierfs94** [comment]
He modificado la regex y simplificado para aceptar un nombre nada más, como si fuera el de un usuario para una página web.
