### ISSUE TITLE
 (+34) 123 456 789 deberías admitirlo

### ISSUE THREAD

**Issue by lmagarin** [Javierfs94/Reentrega-Formulario-Completito#15]
https://github.com/Javierfs94/Reentrega-Formulario-Completito/blob/fd3762fa633c76f56e1d3fd2a1a0def31f383042/js/validar.js#L31

**Comment by Javierfs94** [comment]
No termino de conseguir capturar el (+34). En cuanto a los espacios o que tenga puntos si lo controlo
