### ISSUE TITLE
Lee bien las instrucciones y haz pruebas

### ISSUE THREAD

**Issue by lmagarin** [Javierfs94/Reentrega-Formulario-Completito#16]
Debes cumplir los siguientes requisitos:
- Usa la captura de excepciones
- Evita el uso del for clásico
- Accede a los spans no a través de los ids. Usa las funciones para moverse dentro del árbol DOM
- Utiliza las iteraciones  frente a la duplicación de código.

Asegúrate de validar lo siguiente:
- Obligatoriedad (campo de texto, opción seleccionada (checkbox, radio button y selección)
- Tipo de dato introducido (numérico...)
- Número de teléfono
- válido: (+34) 123 456 789,  (+1907) 123 456 789,  (34) 123 456 789, 34 123 456 789, 34.123.456.789,  123.456.789,  123456789
- NO válido: 12345678

Asegúrate de que:
- Al perder el foco de cada control se comprueba su validación. No funciona en todos
- Al enviar el formulario se realizan TODAS LAS VALIDACIONES, yéndose el foco al primer error. No se va al radio button, ni al select, ni al chec

Procura aislar las validaciones del interfaz del usuario (arquitectura de tres capas)

**Comment by Javierfs94** [comment]
Cierro este issue, puesto que prácticamente controlo todo. Me falta solución un error y alguna regex que tenía pendiente de afinar :)
