### ISSUE TITLE
No controlas que haya un option seleccionada

### ISSUE THREAD

**Issue by lmagarin** [Javierfs94/Reentrega-Formulario-Completito#2]

**Comment by Javierfs94** [comment]
Muy buenas, entiendo que se refiere al option del Sexo. 

Lo estoy revisando y por defecto no hay ninguna seleccionada, y salta el error si se pulsa en Enviar, pero al seleccionar una ya funciona.

Ya me dice para saber donde tirar :)

**Comment by lmagarin** [comment]
Al hacer el blur
Contrólalo en todos
