### ISSUE TITLE
Validar es una especie de LIBRERÍA GENÉRICA para validación. No puedes acceder al árbol DOM

### ISSUE THREAD

**Issue by lmagarin** [Javierfs94/Reentrega-Formulario-Completito#8]
https://github.com/Javierfs94/Reentrega-Formulario-Completito/blob/fd3762fa633c76f56e1d3fd2a1a0def31f383042/js/validar.js#L103
Debes enviar los elemntos radios para ver si están chequeados, la caja de texto, y el valor seleccionado en el select, pero no puedes saber nada más del elemento. Tiene que ser GENÉRICO

**Comment by Javierfs94** [comment]
Solucionado en otro issue de selectores

**Comment by Javierfs94** [comment]
Reabro el issue puesto que no estaba bien hecho la solución y tengo que reformar el código.
